### ISSUE TITLE
Can you share an example of the patterns generated in the README?

### ISSUE THREAD

**Issue by juliohm** [efmanu/BarnsleyFern.jl#14]
It would be nice to learn more about these patterns. Are you aware of the PointPatterns.jl package that is part of the GeoStats.jl stack? We are working on generating patterns over very sophisticated domains, in case you want to join efforts and add the method there instead for greater visibility.

**Comment by efmanu** [comment]
@juliohm : Thanks for your message. I can add the method to generate Barnsley Fern points into PointPatterns.jl

**Comment by juliohm** [comment]
Thank you for considering it @efmanu can you share example visualizations here? I am curious to see what kinds of patterns can be generated.

**Comment by efmanu** [comment]
The pattern is as in the link: https://github.com/efmanu/BarnsleyFern.jl/blob/main/docs/src/anim.gif

**Comment by juliohm** [comment]
That is nice, thanks for sharing. Let us know if you need any help in
PointPatterns.jl

Em seg., 26 de jun. de 2023 11:22, Manu Francis ***@***.***>
escreveu:
